# Generated by Django 5.0.2 on 2024-02-12 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=20)),
                ('image', models.URLField(blank=True)),
                ('concerts', models.JSONField(blank=True)),
                ('followers', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='populate.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True)),
                ('position', models.JSONField()),
                ('weeks_on_list', models.JSONField()),
                ('duration', models.DurationField(blank=True)),
                ('video', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('lyrics', models.TextField(blank=True)),
                ('reproductions', models.JSONField(blank=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='populate.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='populate.artist')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborations', to='populate.artist')),
                ('genre', models.ManyToManyField(blank=True, related_name='songs', to='populate.genre')),
            ],
        ),
    ]
