# Generated by Django 5.0.2 on 2024-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0002_alter_artist_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='concerts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
