# Generated by Django 5.0.2 on 2024-02-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0004_alter_artist_followers_alter_artist_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'artist')},
        ),
    ]
