# Generated by Django 5.0.2 on 2024-02-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0006_alter_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='position',
            field=models.JSONField(null=True),
        ),
    ]
