# Generated by Django 5.0.2 on 2024-02-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0007_alter_song_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='position',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='weeks_on_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
