# Generated by Django 5.0.2 on 2024-02-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0009_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='reproductions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
