# Generated by Django 5.0.2 on 2024-02-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0010_alter_song_reproductions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='weeks_on_list',
        ),
    ]
