# Generated by Django 5.0.2 on 2024-02-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0011_remove_song_weeks_on_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
