# Generated by Django 5.0.2 on 2024-03-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0013_alter_song_unique_together_alter_song_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
    ]
