# Generated by Django 5.0.2 on 2024-03-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0014_remove_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
    ]
