# Generated by Django 5.0.2 on 2024-03-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0016_remove_album_image_remove_artist_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(to='populate.artist'),
        ),
    ]
